# Generated by Django 4.2.6 on 2023-11-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "message_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                ("content", models.CharField(blank=True, max_length=600, null=True)),
                ("sent_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "message",
                "managed": False,
            },
        ),
    ]
